version: "3.7"

services:
  frontend:
    container_name: front-coolie
    env_file:
      - ./.env
    build: 
      context: ./front-coolie
      dockerfile: Dockerfile
      args: 
        PORT: "${PORT_FRONT}"
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    volumes:
      - ./front-coolie:/usr/src/app
    depends_on:
      - back-coolie
  backend:
    container_name: back-coolie
    env_file:
      - ./.env
    build: 
      context: ./back-coolie
      dockerfile: Dockerfile
      args:
        PORT: "${PORT_BACK}"
    ports:
      - "${PORT_BACK}:{PORT_BACK}"
    volumes:
      - ./back-coolie:/user/src/app
volumes: 
  dist:
  mongodata: