version: "3.7"

services:
  backend:
    container_name: back-coolie
    env_file:
      - ./.env
    build:
      context: ./back-coolie
      dockerfile: Dockerfile
      args:
        PORT: "${PORT_BACK}"
    ports:
      - "3333:${PORT_BACK}"
    volumes:
      - ./back-coolie:/app
  frontend:
    container_name: front-coolie
    env_file:
      - ./.env
    build:
      context: ./front-coolie
      dockerfile: Dockerfile
      args:
        PORT: "${PORT_FRONT}"
    ports:
      - "4444:${PORT_FRONT}"
    volumes:
      - ./front-coolie:/app
    depends_on:
      - backend
volumes:
  dist: null
  mongodata: null
